In [29]:
import math
import projectEuler as pE
import pandas as pd

%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

#### Problem 1 : Multiples of 3 and 5
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.

In [7]:
# Problem 1
def problem1(n=1000):
    n = n-1
    cSum = 0

    dbthree = n//3
    dbfive = n//5
    dbfifteen = n//15

    # Applying sum of numbers to be n*(n+1)/2
    cSum = 3*(dbthree*(dbthree+1)) + 5*(dbfive*(dbfive+1)) - 15*(dbfifteen*(dbfifteen+1))
    cSum = cSum>>1

    return(cSum)

problem1()

233168

#### Problem 2 : Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [8]:
# Problem 2
def problem2(n=400000):
    a6 = 0
    a3 = 2
    cSum = 0
    while(a3<=n) :
        cSum,a6,a3 = cSum+a3, a3,4*a3 + a6
    return(cSum)

problem2()

257114

#### Problem 3 : Largest prime factor
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?

In [89]:
def problem3(n=600851475143):
    maxPrime = pE.primeFactors(n).index.max()
    return(maxPrime)
problem3()

6857

In [90]:
#### Problem 4 : Largest palindrome product

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.
Find the largest palindrome made from the product of two 3-digit numbers.

   Count
2      1
7      1
5      1
3      1

In [ ]:
def problem4():
    while(n>=100000 and n < 1000000):
        n = n - 1
        if(pE.isPalindrome(n)):
            for i in range (999,99,-1) :
                if(n%i==0 and n//i <= 999 and n//i >= 100) :
                    return(n)

problem4()